pkg/scripts/install.sh
pkg/scripts/uninstall.sh

Use absolute path for the config file so we don't need to reason about the context from which the scripts are started (and `-chdir` in `terraform apply` command).

TFKUBE-170: Use absolute path for config

---

install.sh

* Resume the `curl` output so it doesn't break the flow of log messages
* Add some logging for the resume Bamboo server action

Silence the curl request

---

install.sh

Now it sets the Synchrony correctly:
```
2022-02-18 17:51:53 [INFO] Resource tags are applied to ASG and all EC2 instances.
2022-02-18 17:51:53 [INFO] Configuring the Synchrony service.
2022-02-18 17:52:10 [INFO] Synchrony URL is set to 'http://a1fe4e953a927473e86e11ad6bb49413-1810032194.ap-southeast-1.elb.amazonaws.com/synchrony'.
```

Fix Synchrony URL pattern

---

config.tfvars
docs/docs/development/HOW_TO_TEST.md
modules/AWS/efs/main.tf
modules/AWS/eks/autoscaling.tf
modules/AWS/eks/locals.tf
modules/AWS/eks/main.tf
modules/AWS/eks/providers.tf
modules/AWS/eks/variables.tf
modules/common/main.tf
modules/products/bitbucket/helm.tf
modules/products/confluence/helm.tf
modules/products/jira/helm.tf
modules/tfstate/main.tf
providers.tf
test/e2etest/bitbucket_test.go
test/e2etest/cluster_test.go
test/e2etest/helper.go
test/e2etest/installer_test.go
test/e2etest/test-config.tfvars.tmpl
test/unittest/eks_test.go
test/unittest/test_variables.go

* add cluster-autoscaler helm release
* create IAM role with necessary permission policy to scale the EKS cluster
* use single subnet for the EKS node group
* enable IRSA (IAM Roles for Service Accounts) in the EKS cluster
* upgrade IAM module to 4.13.2
* add region variable to the EKS module
* add helm provide for EKS module
* add unit tests
* add e2e test case for autoscaler
* decrease the initial e2e capacity to 1 (and expect autoscaler to increase the number of nodes)
* fix developer docs

TFKUBE-201: Add cluster-autoscaler

---

config.tfvars
dc-infrastructure.tf
modules/AWS/eks/main.tf
modules/AWS/eks/outputs.tf
modules/products/bitbucket/helm.tf
modules/products/bitbucket/main.tf
modules/products/bitbucket/nfs/locals.tf
modules/products/bitbucket/nfs/main.tf
modules/products/bitbucket/nfs/nfs-server/.helmignore
modules/products/bitbucket/nfs/nfs-server/Chart.yaml
modules/products/bitbucket/nfs/nfs-server/templates/NOTES.txt
modules/products/bitbucket/nfs/nfs-server/templates/_helpers.tpl
modules/products/bitbucket/nfs/nfs-server/templates/service.yaml
modules/products/bitbucket/nfs/nfs-server/templates/serviceaccount.yaml
modules/products/bitbucket/nfs/nfs-server/templates/statefulset.yaml
modules/products/bitbucket/nfs/nfs-server/values.yaml
modules/products/bitbucket/nfs/variables.tf
modules/products/bitbucket/variables.tf
test/e2etest/bitbucket_test.go
test/unittest/bitbucket_test.go
test/unittest/test_variables.go
variables.tf

* Moved the NFS helm chart to the Terraform project for flexibility reasons
* Add Bitbucket snapshot ID variable (defaults to `null`)
* Expanded the NFS helm chart to include an option to define custom volume claim
* EKS module now returns the single availability zone that is used for the EKS EC2 nodes
* Bitbucket module now explicitly creates the EBS volume (from snapshot if provided), creates PV from it and then PVC that is mounted into NFS server as a shared home
* Dropped `subpath` for the Bitbucket Server helm chart shared home value
* Fixed the E2E test that is verifying a file being written to shared home
* Increased Bitbucket timeout (this should be converted to a variable)
* Increased the default NFS server resources

TFKUBE-412: Add shared home restore

---

config.tfvars
dc-infrastructure.tf
modules/AWS/rds/locals.tf
modules/AWS/rds/main.tf
modules/AWS/rds/variables.tf
modules/products/bamboo/main.tf
modules/products/bamboo/variables.tf
modules/products/bitbucket/main.tf
modules/products/bitbucket/variables.tf
modules/products/confluence/main.tf
modules/products/confluence/variables.tf
modules/products/jira/main.tf
modules/products/jira/variables.tf
test/unittest/bamboo_test.go
test/unittest/bitbucket_test.go
test/unittest/confluence_test.go
test/unittest/database_test.go
test/unittest/jira_test.go
test/unittest/test_variables.go
variables.tf

Previously we implemented the logic to dynamically decide db_name for RDS depending on whether db_snapshot_identifier was used or not. This is because of inconsistency between snapshot provided by dc-apt team and snapshot taken by the data-center-terraform. 
This change will allow users to use input whichever db_name matching with their RDS snapshot

Add DB_NAME to config file

---

config.tfvars
dc-infrastructure.tf
docs/docs/userguide/configuration/BAMBOO_CONFIGURATION.md
docs/docs/userguide/configuration/BITBUCKET_CONFIGURATION.md
docs/docs/userguide/configuration/CONFLUENCE_CONFIGURATION.md
docs/docs/userguide/configuration/JIRA_CONFIGURATION.md
modules/products/bamboo/helm.tf
modules/products/bamboo/variables.tf
modules/products/bitbucket/helm.tf
modules/products/bitbucket/variables.tf
modules/products/confluence/helm.tf
modules/products/confluence/variables.tf
modules/products/jira/helm.tf
modules/products/jira/variables.tf
test/unittest/bamboo_test.go
test/unittest/bitbucket_test.go
test/unittest/confluence_test.go
test/unittest/jira_test.go
test/unittest/test_variables.go
variables.tf

This change exposes the timeout of helm chart installation for each product.
* parameterized the timeout for `helm_release` resource
* exposed the timeout to the top level and config file
* the default timeout is set to the previous value and the default is only on the highest level (`variables.tf`)
* included timeout in the unit tests

TFKUBE-419: Expose timeout for helm chart installation

---

config.tfvars
dc-infrastructure.tf
docs/docs/userguide/configuration/BITBUCKET_CONFIGURATION.md
modules/products/bitbucket/elasticsearch.tf
modules/products/bitbucket/variables.tf
test/unittest/bitbucket_test.go
test/unittest/test_variables.go
variables.tf

This change fixes bug when the user is installing Bitbucket and also redefine the Elasticsearch requests with higher values (beyond the default `limits` values in the [Elasticsearch helm chart](https://github.com/elastic/helm-charts/blob/main/elasticsearch/values.yaml#L94)). It is not possible to have `requests` being higher than `limits` and therefore the Elasticsearch statefulSet fails to deploy.
* Added `elasticsearch_limits_memory`, `elasticsearch_limits_cpu` variables with defaults (double the `requests`).
* Renamed the elasticsearch requests to align them with the `nfs` module
* Added the variables into user documentation
* Fixed the unit tests

TFKUBE-448: Add limits for the elasticsearch helm chart

---

modules/products/jira/helm.tf
modules/products/jira/locals.tf

Valid index snapshot for Jira node should be by default created within 24 hours prior to Jira Node creation. This is an issue as dc-apt team won't distribute new shared-home snapshot everyday.
com.atlassian.jira.startup.max.age.of.usable.index.snapshot.in.hours allows user to customise the period.
It is set to 10 years for now but when jira-server team introduce infinite flag(-1) we can update it later

TFKUBE-453: Add additionalJvmArgs in Jira so It can pick up any existing index snapshot in share-home

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml
providers.tf

Bumping up AWS CLI  version to 2.6.3 still result to `invalid apiVersion "client.authentication.k8s.io/v1alpha1"`.
Tried to update api version to v1beta1(figure 1) but It seems to be that [kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#exec-plugins) only expect `v1alpha1` as an acceptable api_version (figure2).  and the latest kubernetes provider version(2.11.0) doesn't look it it is supporting `v1beta1` yet.
figure1
figure2
Going back to quick-fix solution. locking kubectl version to 1.23.6 worked.

TFKUBE-462: Downgrade kubectl to 1.23.6

---

modules/products/bamboo/helm.tf
modules/products/bamboo/locals.tf
modules/products/bitbucket/helm.tf
modules/products/bitbucket/locals.tf
modules/products/confluence/helm.tf
modules/products/confluence/locals.tf
modules/products/jira/helm.tf
modules/products/jira/locals.tf

* Added `com.atlassian.dcapt.deployment=terraform` property to gather analytics in DCAPT
* Added depedency on the `pre-install` job for Bitbucket
URLs to show property:
Jira - `/jira/secure/admin/ViewSystemInfo.jspa`
Confluence - `/confluence/admin/systeminfo.action`
Bitbucket - `/bitbucket/plugins/servlet/troubleshooting/view/`
Bamboo - `/bamboo/admin/systemInfo.action`

TFKUBE-465: Add DCAPT analytics property

---

config.tfvars
test/unittest/test_variables.go
variables.tf

Update default helm chart versions from `1.2.0` to `1.3.0`.
This PR can serve as a reference for what will need to be changed when we release a new version of helm charts.

TFKUBE-466: Update helm charts from 1.2.0 to 1.3.0

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml
CHANGELOG.md
config.tfvars
docs/docs/userguide/PREREQUISITES.md
install.sh
providers.tf
test/e2etest/bitbucket_test.go
test/unittest/test_variables.go
variables.tf

`aws-iam-authenticator v0.5.5` require `v1beta1` apiVersion for k8s authentication client (replacing `client.authentication.k8s.io/v1alpha1` with `client.authentication.k8s.io/v1beta1` ). 
This caused a failure in provisioning the DC product using terraform project. 
The problem is reported by `dc-app` team and this PR is addressing it by switching the apiVersion to the client.authentication.k8s.io/v1beta1 and right aws cli and Kubernetes version.

CLIP-1587:  Fix the Invalid apiVersion problem

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml

We didn't have scheduled the end to end tests run and in no active development periods, we never find out about test failures. To give more visibility on the health of the repo we should run e2e tests in a logical period of time. 
As there is no frequent change in this repo, and e2e test is an expensive test, testing in every second day basis would be sufficient to keep an eye on the repo health and in the same time not spend much on heavy test process. 
- [-] I have successful end to end tests run (with & without domain)

CLIP-1588: Schedule to run end to end tests on every second day early morning

---

config.tfvars
variables.tf

As we have Helm chart 1.5.0 released for all products, so we should update the default chart versions in terraform solution.

CLIP-1627: Update the default Helm chart version to 1.5.0 for all products

---

config.tfvars
test/e2etest/test-config.tfvars.tmpl
variables.tf

The test fails on installing Confluence Helm chart. Test passes with Confluence Helm chart `1.4.0` but fails with `1.5.0`. I revert the confluence helm chart version to `1.4.0` and create a separated ticket (CLIP-1632) to address this issue in Helm chart repo.

CLIP-1631: Fix terraform e2e test with no domain 

---

docs/docs/userguide/INSTALLATION.md

E2e tests using this solution to provision the infrastructure and run the applications. That was failing because of the Go version. This problem is now fixed. As Helm chart uses the latest release of terraform solution in e2e test, we need to make a new release to the latest changes pick by the e2e test.

CLIP-1635: Release data-center-terraform 2.0.4

---

config.tfvars
dc-infrastructure.tf
modules/products/bamboo/helm.tf
modules/products/bamboo/variables.tf
modules/products/bitbucket/helm.tf
modules/products/bitbucket/variables.tf
modules/products/confluence/helm.tf
modules/products/confluence/variables.tf
modules/products/jira/helm.tf
modules/products/jira/variables.tf
test/unittest/bamboo_test.go
test/unittest/bitbucket_test.go
test/unittest/confluence_test.go
test/unittest/test_variables.go
variables.tf

Under certain conditions application pods are stuck in terminating when a Helm chart is deleted which blocks deletion of a shared home PVC. This results in a timeout error when running uninstall.sh. This PR makes termination grace period configurable in config var file which is passed to helm resource when it's being created. 
No unit tests since this part of pod spec is hidden in kube runtime which isn't available to Terraform.

CLIP-1656: Override termination graceful period

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md
variables.tf

This PR is to release a new version of data-center-terraform.
CLIP-1676: Updated changelog and doc.
CLIP-1676: Updated default Confluence Helm chart version.

CLIP-1676: Release version 2.0.6.

---

test/e2etest/test-config.tfvars.tmpl

Set product termination grace period to 0 to avoid 'pvc still exists with finalizers' error while uninstalling.

CLIP-1674: Fix 'pvc still exists with finalizers' error during uninstallation

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml

Currently, when e2e label is added to a PR, e2e tests are run against main branch which defeats the purpose of having such a label. This small change to workflows fixes it.

Run e2e against branches not only main branch

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml
config.tfvars
modules/products/confluence/locals.tf
test/e2etest/confluence_test.go
test/e2etest/installer_test.go

Currently, synchrony tests are failing https://github.com/atlassian-labs/data-center-terraform/actions/runs/3201163413/jobs/5228854594
This happens because tests use the wrong synchrony url - it has /confluence in it while it should not https://github.com/atlassian/data-center-helm-charts/blob/main/src/main/charts/confluence/templates/ingress.yaml#L40
This PR trims `/confluence` suffix

Fix synchrony test

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml
aws_clean.py
scripts/collect_k8s_logs.sh
test/e2etest/installer_test.go

This PR:
* adds execution of k8s log/event collection script after infra deploy and tests. Here's example of [k8s script execution after tests](https://github.com/atlassian-labs/data-center-terraform/actions/runs/3200843174/jobs/5228210935#step:11:5876). Artifacts are [available here](https://github.com/atlassian-labs/data-center-terraform/actions/runs/3200843174) or [here](https://github.com/atlassian-labs/data-center-terraform/actions/runs/3229788524)
* adds execution of aws cleanup script after running uninstall.sh. Here is [example job](https://github.com/atlassian-labs/data-center-terraform/actions/runs/3200843174/jobs/5228210935#step:11:11065) where uninstall.sh failed to completely delete infra and aws_cleanup.py finishes the job.
* 
PR to data-center-helm-charts …

Collect k8s logs and cleanup AWS resources

---

scripts/collect_k8s_logs.sh

Removing `set -e` as in some cases getting pod logs isn't possible since the pod is in initializing state.

Do not exit log collection script in case of errors

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml

Since we export [PYTHONPATH in cmd.exec](https://github.com/atlassian-labs/data-center-terraform/blob/main/test/e2etest/installer_test.go#L114), Python version should be the same to be able to run aws_clean.py that uses boto3 library.

Pin Python version in setup python workflow step

---

modules/AWS/nfs/main.tf

This PR makes nfs PV-PVC binding bi-directional by using `claimRef` in PV spec which makes it impossible to bind a PV to any PVC but the one that is references in `claimRef`.
This happened a couple of times already to [e2e tests](https://github.com/atlassian-labs/data-center-terraform/actions/runs/3294484301/jobs/5432048390#step:11:4745). Jira helm release is never deployed, and uninstall.sh fails to delete infra because it fails to [delete this PVC](https//github.com/atlassian-labs/data-center-terraform/actions/runs/3294484301/jobs/5432048390#step:11:9910)
After examining logs, it turns out that Jira NFS volume is attached to **elasticsearch** PVC:
```
25m         Normal    SuccessfulAttachVolume   pod/elasticsearch-master-1                                          AttachVolume.Attach …
```

CLIP-1690: Use bi-directional pv binding

---

modules/AWS/asg_ec2_tagging
modules/AWS/dynamodb/provider_version.tf
modules/AWS/eks/provider_version.tf
modules/AWS/ingress/provider_version.tf
modules/AWS/nfs/provider_version.tf
modules/AWS/rds/locals.tf
modules/AWS/rds/main.tf
modules/AWS/rds/outputs.tf
modules/AWS/rds/provider_version.tf
modules/AWS/s3/provider_version.tf
modules/AWS/vpc/provider_version.tf
modules/common/provider_version.tf
modules/products/bamboo/provider_version.tf
modules/products/bitbucket/provider_version.tf
modules/products/confluence/provider_version.tf
modules/products/jira/provider_version.tf
modules/tfstate/provider_version.tf
provider_version.tf
test/unittest/database_test.go

This PR updates aws provider version to 4.36 and rds provider version to 5.1. Both are the latest as of now.
The following attributes were added to rds module (because they are true by default):
```
storage_encrypted          = false
create_random_password     = false
create_db_subnet_group      = true
```
Also, the following was changed in outputs:
```
output "rds_master_password" {
value     = module.db.db_instance_password
sensitive = true
}
```
No changes to any other aws resources.
This fixes a warning on each and every tf apply and destroy
```
Warning: Redundant ignore_changes element  on .terraform/modules/bamboo.database.db/modules/db_instance/main.tf line 20, in resource "aws_db_instance" "this":
20: resource "aws_db_instance" "this" {
```
Important! Run `terraform init --update` …

CLIP-1646: Update aws and rds providers

---

.github/workflows/documentation-build.yaml
.github/workflows/documentation-deploy.yaml
.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml
.github/workflows/unit-test.yaml

This PR bumps versions of used GitHub actions
🟢 https://github.com/atlassian-labs/data-center-terraform/actions/runs/3333209508
There are still a couple of warnings:
* ssh key action - https://github.com/shimataro/ssh-key-action/issues/207
* set-output command deprecation - still pops up even though it's not used in our actions, perhaps it's in one of the used actions themselves

CLIP-1680: Update action versions

---

modules/AWS/rds/main.tf

> auto_minor_version_upgrade bool
Description: Indicates that minor engine upgrades will be applied automatically to the DB instance during the maintenance window. Default: true
This PR sets auto upgrade to minor versions during the upgrade. With `auto_minor_version_upgrade` set to true (which is by default), db is updated and the 2nd terraform apply fails since it tries to downgrade the version.
```
Error: updating RDS DB Instance (atlas-e2etest-ga28xb-confluence-db): InvalidParameterCombination: Cannot upgrade postgres from 11.16 to 11.14
5922	status code: 400, request id: 2679cceb-9c0e-4e1f-845c-18bcf53c9222
5923
5924  with module.confluence[0].module.database.module.db.module.db_instance.aws_db_instance.this[0],
5925  on .terraform/modules/confluence.database.db/modules/db_instance/mai …
```

CLIP-1700: Disable db auto updates

---

modules/AWS/eks/iam.tf
modules/AWS/eks/main.tf

Just a small fixup to https://github.com/atlassian-labs/data-center-terraform/pull/277
It's better to have a unique iam role name to avoid conflicts if for some reason the role isn't deleted.

CLIP-1570: Make iam role name more unique

---

modules/AWS/eks/nodegroup_launch_template/templates/osquery/osquery.sh.tpl
variables.tf

5.5.1 seems to have issues when started with a debug flag. The instances stop reporting logs after some time. Osquery 5.4.0 is recommended. Debug flags are dropped too.

Install osquery 5.4.0 and drop debug flag

---

.gitignore
test/e2etest/installer_test.go

The issue with terraform apply 2 times in a row cannot be reproduced anymore. See:
* https://github.com/atlassian-labs/data-center-terraform/actions/runs/3457214411/jobs/5770494962#step:11:5251
* https://github.com/atlassian-labs/data-center-terraform/actions/runs/3457914723/jobs/5771815875#step:11:5261
Perhaps, updating AWS provider version has fixed it.

CLIP-1673: Test with domain install 2 times in a row

---

modules/AWS/asg_ec2_tagging
modules/AWS/eks/nodegroup_launch_template/templates/osquery/osquery.sh.tpl
modules/products/bamboo/helm.tf
modules/products/bitbucket/helm.tf
modules/products/confluence/helm.tf
modules/products/jira/helm.tf
test/e2etest/test-config.tfvars.tmpl
variables.tf

This PR fixes an issue with pods stuck in a Terminating state when destroying infrastructure. The problem was with the deletion of a shared home pvc which is stuck in pending as long as its pod is stuck in Terminating.
Helm release server pods are often stuck in terminating (unless termination grace period is set to 0) because of the following reason:
Destruction of nfs module (that includes nfs helm release and EBS volume with PV and PVCs) and product helm releases happens almost simultaneously, as a result, when, say, confluence pod is in Terminating state (preStop hook can take some time), EBS volume that backs the underlying PV and PVCs gets destroyed too. As a result, confluence container enters a weird state, and kubelet cannot kill the pod because of the following error:
```
tried …
```

CLIP-1701: Wait until pods in Helm release are terminated before destroying nfs module

---

config.tfvars
dc-infrastructure.tf
locals.tf
modules/products/bitbucket/helm.tf
modules/products/bitbucket/locals.tf
modules/products/bitbucket/variables.tf
modules/products/jira/helm.tf
modules/products/jira/locals.tf
modules/products/jira/variables.tf
test/unittest/bamboo_test.go
variables.tf

This PR adds support of installing local Helm charts for Jira and Bitbucket (smth that is there for Confluence and Bamboo), as well as unsets defaults for Helm chart version. When Helm chart versions are explicitly set they need to be constantly updated. When no version is provided, helm_release resource will automatically use the latest. It'll still be possible to override helm chart version, i.e. existing behavior is unchanged.

CLIP-1708: Fix use of local helm charts

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml
test/e2etest/helper.go
test/e2etest/installer_test.go
test/e2etest/test-config.tfvars.tmpl
test/unittest/eks_test.go
test/unittest/test_variables.go

This PR adds Atlassian role defined by a secret in actions to [aws_auth_roles](https://github.com/atlassian-labs/data-center-terraform/blob/main/modules/AWS/eks/main.tf#L37) which makes it possible to get access to EKS clusters created by e2e iam user by assuming the role defined in the actions secret.
e2e https://github.com/atlassian-labs/data-center-terraform/actions/runs/3484569813/jobs/5829262631 (can't use the label since workflows are used from master)

CLIP-1630: Add additional role to e2e tests

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml
scripts/send_slack_notifications.sh

The suggested script uses incoming webhooks (one per channel) as message delivery method. The information in the message is pretty straightforward - commit, author, event type, link to PR if this is a PR.

CLIP-1633: Send slack notifications with build statuses

---

modules/AWS/asg_ec2_tagging
test/e2etest/bitbucket_test.go

Adding 2 simple ES tests:
* check if 2 bitbucket indexes are green
* check if `docs.count` == count of projects and repos respectively.
1 project and 1 repo is created in `assertBitbucketSshConnectivity`, and `assertEsIndexes` is making sure that doc.count in respective indexes is 1.
Rather that wait and try for a long time, the test will make 2 attempts to verify indexes. It takes a few seconds for indexes to reflect changes in `docs.count` after a project and a repo are created.

CLIP-1533: Add ElasticSearch e2e tests

---

uninstall.sh

`uninstall.sh` may fail to destroy infra if terraform apply has been unsuccessful:
```
module.base-infrastructure.module.eks.aws_autoscaling_group_tag.this["Name"]: Refreshing state... [id=eks-appNode-t3_xlarge-50c26268-ea57-5aee-4523-68f33af7dd71,Name]
Error: Unsupported attribute
on dc-infrastructure.tf line 142, in module "confluence":
142: ingress = module.base-infrastructure.ingress
├────────────────
│ module.base-infrastructure is object with 5 attributes
This object does not have an attribute named "ingress".
Error: Unsupported attribute
on modules/AWS/rds/locals.tf line 4, in locals:
4: db_jdbc_connection = "jdbc:postgresql://${module.db.db_instance_endpoint}/${var.product}"
├────────────────
│ module.db is object with 12 attributes
This object does not have an attribute named …
```

CLIP-1727: Skip refresh when destroying

---

CHANGELOG.md
docs/docs/troubleshooting/TROUBLESHOOTING.md
docs/docs/userguide/INSTALLATION.md
test/e2etest/installer_test.go
uninstall.sh

While https://github.com/atlassian-labs/data-center-terraform/pull/291 fixes the error when destroying terraform after a failed terraform apply, it introduces another issue. Skipping refresh can sometimes make Helm provider keep using an invalidated token, which results in the following error:
```
Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials
```
This PR makes `-refresh=false` optional, and it can be added to terraform destroy args with `-s` flag. 2 additional FAQs were added as well.

CLIP-1734: Make skip refresh optional

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md
uninstall.sh

Fix a bug with failing ininstall.sh without -s flag

CLIP-1743: Fix tf destroy when -s isn't provided

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml
aws_clean.py
test/e2etest/installer_test.go

This PR adds an official [AWS action](https://github.com/aws-actions/configure-aws-credentials) to assume a role (saved in actions secrets)
Ran from a branch https://github.com/atlassian-labs/data-center-terraform/actions/runs/3722634095/jobs/6313620095 since workflows are retrieved from master only.

CLIP-1729: Assume IAM role to configure  AWS credentials for tests

---

modules/AWS/ingress/locals.tf
modules/AWS/ingress/main.tf
modules/AWS/ingress/variables.tf
modules/AWS/vpc/outputs.tf
modules/common/locals.tf
modules/common/main.tf
test/unittest/ingress_test.go
test/unittest/test_variables.go

This PR fixes an issue with Confluence being unable to reach Synchrony using ingress URL when `whitelist_cidr` restricts access to a particular range. Since private subnets use NAT, we need to silently add NAT EIP to whitelist_cird, unless it's all-permissive `0.0.0.0/0`

CLIP-17-52: Add NAT IP to whitelist_cidr

---

config.tfvars
docs/docs/userguide/configuration/BAMBOO_CONFIGURATION.md
docs/docs/userguide/configuration/BITBUCKET_CONFIGURATION.md
docs/docs/userguide/configuration/CONFLUENCE_CONFIGURATION.md
docs/docs/userguide/configuration/JIRA_CONFIGURATION.md
modules/AWS/rds/locals.tf
modules/AWS/rds/main.tf
modules/AWS/rds/variables.tf
test/unittest/confluence_test.go
test/unittest/database_test.go
test/unittest/test_variables.go

This PR forces Terraform to rely on engine_version from a db snapshot if defined rather than on supplied values in tfvars file. This will fix the issue when snapshot db version differs from the one in tfvars.
Tested locally by using a snapshot with 11.4 version and setting 13.4 in tfvars. The first apply was a success and 11.4 db was created, the second one said there were no changes, i.e. engine version values from tfvars are ignored if db snapshot is defined.
Writing a unit test is somewhat problematic since the actual version is read from a real snapshot. To the contrary, I had to remove db snapshot identifier from unit tests as I found no way to avoid reading data and using some mock that would make Terratest happy. However, the logic around supplying db snapshot hasn't been changed …

CLIP-1749, CLIP-1744: Read engine_version from snapshot. Support Postgres 14

---

modules/AWS/eks/main.tf
modules/AWS/eks/nodegroup_launch_template/main.tf
modules/AWS/eks/nodegroup_launch_template/variables.tf
test/e2etest/cluster_test.go
test/e2etest/installer_test.go

`disk_size` in node group settings is ignored if a custom launch template is used. Moving ebs config to launch tempalte.
Added an [e2e test](https://github.com/atlassian-labs/data-center-terraform/pull/303/files#diff-6afb0bd2b96fbd68692fc79175b6bc446cb66721bbe7f07fb693df9d57fc5bdfR54) to check the actual default EBS vol size (50Gi)

CLIP-1771: Fix instance disk size

---

modules/AWS/eks/nodegroup_launch_template/locals.tf
modules/AWS/eks/nodegroup_launch_template/templates/osquery/osquery.sh.tpl
test/unittest/eks_test.go
variables.tf

Something may have changed in the way aws cli is installed, and it's not available at /us/local/bin/aws anymore.
Also, a local var with osquery version was actually unused. This PR changes the default value in root level vars.

Call aws without absolute path

---

helm-charts/nfs-server/Chart.yaml

Use updated nfs server test image with ganesha v4.x - https://hub.docker.com/layers/atlassian/nfs-server-test/2.1/images/sha256-488817857d671ea209855d4187fb9cd45c39e22d3fb8b8cd97e95ec2e5246c37?context=explore
Previous 2.0 tag had issues which sometimes made Bitbucket scaling impossible. From time to time we see the following error when trying to scale Bitbucket:
```
2023-01-31 21:01:04,693 ERROR [spring-startup]  c.a.s.internal.home.HomeLockAcquirer Lock file /var/atlassian/application-data/shared-home/.lock cannot be obtained in home directory /var/atlassian/application-data/shared-home. Does bitbucket have write permission on that directory? Is file locking enabled for the filesystem?
```
NFS logs go as follows:
```
31/01/2023 21:01:04 : epoch 63d8bc49 : bitbucket-nfs-server-0 : …
```

CLIP-1757: Update nfs helm chart appVersion

---

modules/AWS/eks/nodegroup_launch_template/locals.tf

Template does not need this var, as the role arn is computed in locals and passed as `aws_sts_arn_role`.

Remove unused variable passed to templates

---

config.tfvars
modules/AWS/eks/locals.tf
modules/AWS/eks/variables.tf
modules/common/variables.tf
modules/products/bitbucket/locals.tf
variables.tf

EKS 1.25 is available now while 1.21 has reached EOL ([proof](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar)). This PR bumps EKS version, as well as versions of 2 Helm charts that have PodDisruptionBudget in their templates. In 1.25 PDB has migrated from [policy/v1beta1 to policy/v1](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125) which has been fixed in more recent Helm chart versions.

CLIP-1779: Update EKS to 1.25

---

modules/AWS/eks/locals.tf
modules/AWS/eks/outputs.tf
outputs.tf

Fixing occasional error:
```
Error: Output refers to sensitive values
on outputs.tf line 11:
11: output "eks" {
To reduce the risk of accidentally exporting sensitive data that was intended
to be only internal, Terraform requires that any root module output
containing sensitive data be explicitly marked as sensitive, to confirm your
intent.
If you do intend to export this data, annotate the output value as sensitive
by adding the following argument:
sensitive = true
```
Since cluster name is explicitly set, no need to get it from module's outputs. Also, removing asg name from outputs since it's not used.

Update eks output

---

Dockerfile

Add Dockerfile base image ARG to have the ability for simple base image override for local CI usage.

Update Dockerfile with base image ARG

---

aws_clean.py
modules/AWS/eks/main.tf
modules/AWS/eks/nodegroup_launch_template/main.tf

Changes in this PR:
* use `name_prefix` for launch template instead of a name (always good to use it to avoid already exist errors in cases when uninstall failed and the infra was cleaned up with some script)
* add delete iam roles and policies functions to AWS cleanup script
* add delete launch templates function to AWS cleanup script

Use name prefix for launch template. Delete IAM roles and policies

---

Dockerfile
uninstall.sh

As cluster could be in a broken state or in the case of Docker deployment modules folder is not exist and need to do init anyway.

Always do init during unistall.sh

---

modules/products/crowd/helm.tf

There are race conditions and often Crowd pod is up before the DB is ready.

CLIP-1815: Crowd Helm release must depend on DB

---

install.sh

This PR adds a new optional flag (`-p`) and function that will check if RDS and EBS snapshots exist (and are public) and that they are compatible with the installed product version. The goal is not to let a user start creating infrastructure with RDS/EBS snapshots incompatible with the deployed product version.
How versions are being checked?
**EBS**
The check depends on the **EBS description** and it expects to find `dcapt-<product>-<version>` in the description. If the description does not contain `dcapt` the check will fail. The function will attempt to extract version from the description (replacing any `-` with `.`).
**RDS**
RDS snapshot **arn** is used to extract the version. The function expects that the arn contains `dcapt-<product>-<version>` pattern and will try to extract the …

CLIP-1812: Pre-flight EBS/RDS checks

---

uninstall.sh

Existing Terraform way of removing S3 bucket and DynamoDB does not work. Terraform says there's 0 resources to delete. In debug logs we see:
```
2023-08-02T18:01:20.788+1000 [DEBUG] pruneUnusedNodes: local.bucket_key (expand) is no longer needed, removing
2023-08-02T18:01:20.788+1000 [DEBUG] pruneUnusedNodes: module.tfstate-bucket.aws_s3_bucket.terraform_state (expand) is no longer needed, removing
2023-08-02T18:01:20.788+1000 [DEBUG] pruneUnusedNodes: module.tfstate-bucket.var.bucket_name (expand) is no longer needed, removing
2023-08-02T18:01:20.788+1000 [DEBUG] pruneUnusedNodes: module.tfstate-table.var.dynamodb_name (expand) is no longer needed, removing
2023-08-02T18:01:20.788+1000 [DEBUG] pruneUnusedNodes: module.tfstate-bucket.var.required_tags (expand) is no longer needed, …
```

CLIP-1814: Remove S3 bucket and Dynamodb

---

modules/products/bamboo/helm.tf
modules/products/bamboo/locals.tf

Cleaned up Bamboo additional environment variable - ATL_BASE_URL, since Helm chart already handles this for us.

Cleaned up Bamboo additional environment variable - ATL_BASE_URL

---

permissions/assume-role.sh
permissions/policy.json
permissions/test-permission.md
permissions/update-policy.sh
test/unittest/snapshots_test.go

This PR provided a guided set of policy statements for the AWS IAM role that runs the Terraform deployment. With more clearly defined services and actions in the policy, users no longer need admin permission for the deployment. 
Also, two scripts are added to facilitate testing for future use, i.e. script to assume a role, and script to update policy statement using CLI and policy document instead of doing the update manually via AWS console.

CLIP-1883: Role permissions
