atlassian-labs/data-center-terraform

config.tfvars
docs/docs/userguide/CLEANUP.md
docs/docs/userguide/CONFIGURATION.md
docs/docs/userguide/INSTALLATION.md
docs/docs/userguide/PREREQUISITES.md

TFKUBE-205: Add docs for dataset import

---

docs/docs/development/HOW_ADD_PRODUCT.md
docs/docs/development/HOW_TO_START.md
docs/docs/development/HOW_TO_TEST.md

This PR contains the changes I made to the development content. The changes include linguistic, structural, and content improvements. Some of them may be significant, so a thorough verification of the work is required.
I noticed that the dev & test environment requirements are repeated a few times. Expect another pull request with suggested edits.

[TFKUBE-190] Review & edit development content

---

install.sh
modules/products/confluence/helm.tf
modules/products/confluence/locals.tf

It is not perfect but I found this solution much easier simpler than trying to proactively create an elastic IP and then convince the new LoadBalancer to assign to it.

TFKUBE-322: Add support for collaborative editing if no domain is provided

---

config.tfvars
dc-infrastructure.tf
docs/docs/userguide/configuration/BAMBOO_CONFIGURATION.md
docs/docs/userguide/configuration/BITBUCKET_CONFIGURATION.md
docs/docs/userguide/configuration/CONFIGURATION.md
docs/docs/userguide/configuration/CONFLUENCE_CONFIGURATION.md
docs/docs/userguide/configuration/JIRA_CONFIGURATION.md
locals.tf
modules/products/bitbucket/helm.tf
modules/products/bitbucket/locals.tf
modules/products/bitbucket/variables.tf
test/unittest/bitbucket_test.go
variables.tf

This PR added support for Bitbucket display name.

TFKUBE-330: Bitbucket display name

---

config.tfvars
dc-infrastructure.tf
docs/docs/userguide/configuration/JIRA_CONFIGURATION.md
modules/AWS/rds/locals.tf
modules/AWS/rds/main.tf
modules/AWS/rds/variables.tf
modules/products/jira/helm.tf
modules/products/jira/locals.tf
modules/products/jira/main.tf
modules/products/jira/variables.tf
test/unittest/database_test.go
test/unittest/jira_test.go
test/unittest/test_variables.go
variables.tf

TFKUBE-401:  Jira snapshot restore

---

scripts/cleanup.sh

TFKUBE-414: Added Bitbucket, Jira, and Confluence modules in cleanup script

---

docs/docs/troubleshooting/TROUBLESHOOTING.md

Add to troubleshooting guide how to retrieve application log and ssh to application node

TFKUBE-418: Updated to troubleshooting guide - SSH to pod and Log access

---

docs/docs/userguide/configuration/BITBUCKET_CONFIGURATION.md

Organised the Bitbucket configuration documentation

---

docs/docs/userguide/configuration/BAMBOO_CONFIGURATION.md
docs/docs/userguide/configuration/CONFLUENCE_CONFIGURATION.md

TFKUBE-429: Organised the Bamboo and Confluence configuration documentation

---

test/unittest/bitbucket_test.go
test/unittest/nfs_test.go
test/unittest/test_variables.go

Unit test updated to run against independent nfs module

TFKUBE-435: Update unit test nfs

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml
modules/products/bitbucket/helm.tf

TFKUBE-445: Changed back Bitbucket helm chart install timeout to 15 min

---

docs/requirements.txt
go.mod
go.sum

Upgrade dependencies to remove all detected vulnerabilities.
```
snyk test --all-projects                                                                                                                                                                                       12:59:17
Testing /Users/abrokes/code/data-center-terraform...
Organization:      engineering-container-scanning
Package manager:   gomodules
Target file:       go.mod
Project name:      github.com/atlassian-labs/data-center-terraform
Open source:       no
Project path:      /Users/abrokes/code/data-center-terraform
Licenses:          enabled
✔ Tested 523 dependencies for known issues, no vulnerable paths found.
Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of …
```

TFKUBE-455: Update the dependencies

---

README.md
docs/docs/README.md
docs/docs/userguide/INSTALLATION.md
docs/docs/userguide/PREREQUISITES.md
docs/docs/userguide/configuration/CONFIGURATION.md

Documentation updates that were done part of documentation review mob session.

TFKUBE-305: Review docs

---

modules/products/confluence/locals.tf
test/e2etest/bitbucket_test.go

This PR fixed end-to-end tests. Two issues were:
- Invalid interpolation values while planning:  var.db_master_username and var.db_master_password
- Deprecated API version client.authentication.k8s.io/v1alpha1

Tfkube 467 e2e test failure

---

docs/docs/troubleshooting/LIMITATIONS.md
docs/docs/troubleshooting/TROUBLESHOOTING.md

This PR expanded troubleshooting and limitation documentation with:
- Bitbucket scale up issue with NFS
- Limitation on switching between domain and no domain
- Troubleshooting tips on how to deal with persistent volume claim destroy failed error 
- How to clean up resources if installation failed.
- EIP address limits exceeded solution

TFKUBE-449: Troubleshooting and limitation documentation

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

This PR releases new version 2.0.0.

TFKUBE-300: Release 2.0.0

---

CHANGELOG.md
config.tfvars
test/unittest/test_variables.go
variables.tf

As the new version of Helm charts are released, this PR upgrade to the latest available helm chart version for all products, 1.4.0

CLIP-1590: Upgraded helm chart versions to 1.4.0

---

config.tfvars
docs/docs/userguide/INSTALLATION.md

CLIP-1623: Release version 2.0.3

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml
.github/workflows/unit-test.yaml

Update `setup-go` action to the latest as it became flaky.

Fix the setup-go github action

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/unit-test.yaml
modules/AWS/eks/locals.tf
modules/AWS/eks/main.tf
modules/AWS/nfs/helm.tf
modules/AWS/nfs/persistent_volume.tf
modules/AWS/nfs/variables.tf
modules/common/main.tf
modules/products/bamboo/locals.tf
modules/products/bamboo/main.tf
modules/products/bitbucket/locals.tf
modules/products/bitbucket/main.tf
modules/products/bitbucket/pre_install.tf
modules/products/confluence/locals.tf
modules/products/confluence/main.tf
modules/products/confluence/pre_install.tf
modules/products/jira/locals.tf
modules/products/jira/main.tf
modules/products/jira/pre_install.tf
test/e2etest/installer_test.go
test/unittest/nfs_test.go
test/unittest/test_variables.go

DCAPT team reported the terraform cycle error. This only happens on second run of install.sh as terraform tries to replace products PV due to dynamic provision of NFS service IP.
[
](url)
This PR is to avoid the unnecessary replacement action by providing static IP address to every NFS servers' serviceIP.
Also E2E test will run install.sh script twice to cover use case of 're-apply'.

CLIP-1641: Resolve EKS Cycle Issue

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

CLIP-1664: Release data-center-terraform 2.0.5

---

scripts/collect_k8s_logs.sh

Adding a small script to collect k8s logs and events to be able to better understand helm chart installation issues
No end to end tests since the script isn't integrated into any workflows at the moment

Add k8s debug script

---

.github/CODEOWNERS

Add bianchi2 to codeowners

---

CHANGELOG.md
config.tfvars
dc-infrastructure.tf
docs/docs/userguide/configuration/CONFLUENCE_CONFIGURATION.md
modules/products/confluence/helm.tf
modules/products/confluence/locals.tf
modules/products/confluence/variables.tf
test/unittest/confluence_test.go
test/unittest/test_variables.go
variables.tf

Add configuration to customise the synchrony instance:
- CPU
- Memory
- JVM max/min heap size and stack size

CLIP-1677: Introduced the configuration for Synchrony instance

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

CLIP-1684: Release 2.1.0

---

CONTRIBUTING.md

CLIP-1691: Add notes on how to release.

---

CHANGELOG.md
CONTRIBUTING.md
docs/docs/userguide/INSTALLATION.md

Minor release as it contains a slight behavioural change (bidirectional PV)
- [/] I have user documentation (if applicable)

CLIP-1699: Update versions for 2.2.0 release.

---

.github/workflows/e2e-test-no-domain.yaml
.github/workflows/e2e-test-with-domain.yaml

Use the latest version of upload ssh key action as per https://github.com/atlassian-labs/data-center-terraform/pull/274#issuecomment-1302838206

Bump ssh key action version

---

docs/docs/README.md
docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md

Minor updates
- [NA] I have successful end to end tests run (with & without domain)
- [NA] I have added unit tests (if applicable)

Update support wording

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

Updates to changelog and installation docs to prepare for 2.2.0 release

CLIP-1718: Release 2.2.0

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

Update changelog and installation instructions

CLIP-1728: Release 2.2.1

---

aws_clean.py

Make sure there are abandoned hosted zones and certificates which can be orphaned after a possible failure to run terraform destroy.

CLIP-1697: Delete abandoned hosted zones and certificates

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

Update changelog and installation instructions

Prepare to release 2.2.4

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

Release 2.3.0

---

scripts/collect_k8s_logs.sh

Not all apps send logs to stdout/err, thus it can be very helpful to get complete logs to troubleshoot issues, especially when it comes to performance issues. The entire logs directory is copied from each pod.

Get log files from pods

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

Release 2.3.1

---

config.tfvars
dc-infrastructure.tf
modules/AWS/eks/iam.tf
modules/AWS/eks/locals.tf
modules/AWS/eks/main.tf
modules/AWS/eks/nodegroup_launch_template/locals.tf
modules/AWS/eks/nodegroup_launch_template/main.tf
modules/AWS/eks/nodegroup_launch_template/variables.tf
modules/AWS/eks/osquery.tf
modules/AWS/eks/variables.tf
modules/AWS/ingress/locals.tf
modules/AWS/ingress/main.tf
modules/AWS/rds/locals.tf
modules/AWS/rds/main.tf
modules/common/main.tf
modules/common/variables.tf
modules/products/confluence/helm.tf
modules/products/confluence/locals.tf
variables.tf

fix validation error

---

Dockerfile
install.sh

Docker with tools

---

Dockerfile

improve description inside Dockerfile

---

Dockerfile

Change Docker name to use public one. Latest tag will be available after new data-center-terraform release.

Update docker name

---

Dockerfile

One more improvement for Dockerfile description

Better description for dockerfile

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

Release 2.5.0

---

install.sh

This PR makes bash syntax compatible with bash 3, as well as fixes snap description check.

Fix pre-flight check

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

Release 2.6.0

---

config.tfvars
dc-infrastructure.tf
docs/docs/userguide/configuration/CONFLUENCE_CONFIGURATION.md
modules/products/confluence/helm.tf
modules/products/confluence/locals.tf
modules/products/confluence/opensearch_storage.tf
modules/products/confluence/provider_version.tf
modules/products/confluence/secrets.tf
modules/products/confluence/variables.tf
provider_version.tf
providers.tf
test/unittest/confluence_test.go
variables.tf

This PR enables OpenSearch PV restoration if EBS volume id is provided. 
Also, persistence volume size is also made configurable.

DCCLIP-913: Restore OpenSearch from snapshot

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

DCCLIP-917: Prepare release for 2.8.0

---

.github/workflows/update-policy.yaml
permissions/update-policy.sh

This PR added a new Github Action to automatically update AWS IAM policy that's used for e2e test CI when the `policy.json` file is modified. It'll only be triggered when changes are merged into the main branch.

CLIP-1903: New GitHub action to update policy

---

permissions/policy.json

This PR added more permissions to `policy.json` file which are identified through a few e2e test runs.

CLIP-1903: Add Missing permissions

---

permissions/atlassian-policy.json

This PR added Atlassian specific policy to facilitate testing.

CLIP-1903: Added Atlassian specific policy.

---

CHANGELOG.md
docs/docs/userguide/INSTALLATION.md

Release 2.9.2

---

modules/AWS/rds/locals.tf

Bump RDS versions in local.tf
